[package]
name = "http2"
version = "1.0.0"
edition = "2018"

[dependencies]
actix-web = { version = "2.0", features = ["openssl"] }
actix-rt = "1.0"
openssl = { version = "0.10", features = ["v110"] }
