title = "actix"
canonifyURLs = true
googleAnalytics = "UA-110322332-1"
pygmentsUseClasses = true
pygmentsCodeFences = true
defaultContentLanguageInSubdir = false
enableRobotsTXT = true
enableMissingTranslationPlaceholders = true
DefaultContentLanguage = "en"
baseURL = "https://actix.rs"

[languages.en]
languageCode = "en-US"
languageName = "English"
weight = 1

[params]
actixVersion = "0.10"
actixWebVersion = "3"
actixRtVersion = "1.1"
actixWebMinRustVersion = "1.42"
actixMinRustVersion = "1.42"
