[package]
name = "requests"
version = "1.0.0"
edition = "2018"

[dependencies]
serde = "1.0"
serde_json = "1.0"
actix-web = "3.0.0-beta.4"
actix-rt = "1"
futures = "0.3.1"
bytes = "0.4"
actix-multipart = "0.2"
