[package]
name = "server"
version = "1.0.0"
workspace = "../"
edition = "2018"

[dependencies]
actix-rt = "1.0"
actix-web = { version = "2.0", features = ["openssl"] }
futures = "0.3.1"
openssl = "0.10"
actix-http = "1.0"
