[package]
name = "url-dispatch"
version = "1.0.0"
edition = "2018"
workspace = "../"

[dependencies]
actix = "0.9"
actix-rt = "1"
actix-web = "3.0.0-beta.4"
futures = "0.3.1"
openssl = "0.10"
serde = "1.0"
